default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADAS") { 5000 } %>
  timeout: 50000

development:
  <<: *default
  database: db/development.sqlite3
  timeout: 30000

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
